name: Deploy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Сборка образа и деплой в Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: anclaev/com
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ../../Dockerfile
